version: "3.7"
services:
  app:
    entrypoint:
    - sleep
    - infinity
    init: true
    build: .
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

