services:
  app:
    image: ghcr.mirror.nbtca.space/wen-templari/sponge:latest
    entrypoint:
    - sleep
    - infinity
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

