name: ci

on:
  push:
    branches: ["dev"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sponge
  IMAGE_NAME_FULL: ghcr.io/wen-templari/sponge

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME_FULL }}:latest